### ISSUE TITLE
New HMM code update messes sound handle

### ISSUE THREAD

**Issue by BatmanSonic758** [hedge-dev/HMMCodes#110]
Working on an update of a mod of mine, everything worked fine, until the HMM library got updated and that messed up sound handles, thus makes the sounds repeat themselves after being played first. In other words, the sound doesn't stop like they used to before the library update.

A code like this for example:

static bool isStompingDownTails = false;
static int TailsStompDownSoundHandle = -1;

{
    if (Player.GetPlayerType() != Player.PlayerType.Tails)
        return;

    Tails.StateID currentState = Player.State.GetCurrentStateID<Tails.StateID>();

    if (currentState == Tails.StateID.TailsStateStompingDown)
    {
        if (!isStompingDownTails)
        {
            TailsStompDownSoundHandle = Player.Sound.PlaySound("ta_fly_loop"); // Change to the appropriate sound file

            if (TailsStompDownSoundHandle != -1)
            {
                isStompingDownTails = true;
            }
            else
            {
                // Handle sound play error, e.g., print a message or log an error
            }
        }
    }
    else
    {
        if (isStompingDownTails)
        {
            int soundHandle = TailsStompDownSoundHandle;
            Player.Sound.StopSound(&soundHandle);
            TailsStompDownSoundHandle = soundHandle;
            isStompingDownTails = false;
        }
    }
}

**Comment by hyperbx** [comment]
I'm not sure what the issue could be here, as I don't recall changing any sound implementation when updating the APIs.
