### ISSUE TITLE
[Sonic Generations] Analog sticks don't work when "Fix Input Delay with Arbitrary Framerates (experimental)" is enabled

### ISSUE THREAD

**Issue by ZippyZolton** [hedge-dev/HMMCodes#116]
Title says it all, moving from a standstill will usually do not do much if anything, you can only change your direction if you're already moving with something else. Had this issue for a long time, but didn't find out the cause until now.

Here is a video demonstrating how it feels with the code on (extending my left stick all the way left and right), and then showing that the issue doesn't happen with the code off;

https://github.com/hedge-dev/HMMCodes/assets/28773304/82ab3b72-e6a3-408e-9fbc-521464d24361

**Comment by ZippyZolton** [comment]
This exact issue also happens with the "Locked 144 FPS (experimental)" code.

**Comment by blueskythlikesclouds** [comment]
This is a high refresh rate problem which is a bug ingrained into the game's code base, there isn't much the code can do.

**Comment by ZippyZolton** [comment]
Yeah... I'm surprised things work at all with how far the modifications have gone.

**Comment by blueskythlikesclouds** [comment]
Well, I'll be closing this, then. Fixing this would be through a mod that actually focuses on fixing HFR issues.
