### ISSUE TITLE
HMM Library crashes the game on boot when ran on a Steam Deck.

### ISSUE THREAD

**Issue by DeaTh-G** [hedge-dev/HMMCodes#135]
Using the HMM library to handle configurable options for a mod will make the game crash on boot on Steam Deck. Issue likely lies at: https://github.com/hedge-dev/HMMCodes/blob/main/Source/Globals/Libraries/HMM.hmm#L13 due to HMM and the game not running in the same prefix, meaning they don't share registry.

Besides it causing this issue according to @Sajidur78 this is also a dangerous thing to do because it could lead to a different ini file based on how the game was launched.

**Comment by hyperbx** [comment]
Fixed in commit https://github.com/hedge-dev/HMMCodes/commit/9ca8272c042aaeaa9bf89a5964d6617f7e4defd9.
