### ISSUE TITLE
Sonic Frontiers: "Disable Traversal Objects in Chests" causes springs to be targeted by the homing attack in "Bridge the Gap"

### ISSUE THREAD

**Issue by Optimus-Bull** [hedge-dev/HMMCodes#142]
Like the title says.
One or more codes are causing springs to be targeted by the homing attack in the "bridge the gap" mission.

Making it unclearable as you can't properly homing attack the enemies to dive faster down.
I know one or more codes are causing this issue.

I'm still in the process of trying to figure out which code affects this, but so far no luck.

Update:
I figured out exactly which code is causing the issue.
"Disable Traversal Objects in Chests"

That one is causing the springs in "Bridge the Gap" to be targeted by the homing attack.
Disabling it fixes the issue.

**Comment by Optimus-Bull** [comment]
I just want to clarify that even without the code, some springs are of course meant to be targeted by the homing attack. Like the ones meant to be used as shortcuts to dive faster towards the ground.

But the extra springs placed close together, pointing upwards that serves as blockades & obstacles that slow you down, all of those get targeted by the code when they otherwise shouldn't.

**Comment by hyperbx** [comment]
Fixed in commit https://github.com/hedge-dev/HMMCodes/commit/5590e4967278902c9075e44ad216365e8250e270, closing...
