### ISSUE TITLE
[Sonic Frontiers] Disable FPS Limit code not working

### ISSUE THREAD

**Issue by OmuNaki** [hedge-dev/HMMCodes#164]
As title says, the code is activated but in-game and with both RivaTuner and Steam's overlay the game is still locked at 60fps. Before Update 2 I remember it working properly but ever since that update it hasn't worked.

**Comment by hyperbx** [comment]
Does your display support higher than 60Hz?

**Comment by OmuNaki** [comment]
Yes, it's a 240hz monitor.

**Comment by hyperbx** [comment]
Enable the `Show Frame Rate on Title Bar` code under the System category and see what that reports, it should be a metric provided during every frame.

**Comment by OmuNaki** [comment]
![Screenshot_6](https://github.com/user-attachments/assets/125fb196-0f9e-4f60-b3ba-b3db6773d008)

No mods, only the Disable FPS Limit and Show Framerate codes on

**Comment by hyperbx** [comment]
Does the frame rate increase if you disable V-Sync in the game settings?

**Comment by OmuNaki** [comment]
No, it stays the same wether on or off.

**Comment by hyperbx** [comment]
Create a file in your mods directory called `ExtraCodes.hmm` and paste the following into there;

```cs
Code "Verify Disable FPS Limit"
//
    #lib "GameMode"
    #lib "Memory"

    static bool _isPrinted = false;
//
{
    if (GameMode.GetName() != "GameModeTitle")
        return;

    if (_isPrinted)
        return;
    
    Console.WriteLine();
    Memory.PrintMemory((nint)0x140D64D50, 2);
    Console.WriteLine();
    Memory.PrintMemory((nint)0x140D64E21, 2);
    Console.WriteLine();
    Memory.PrintMemory((nint)0x140146A1C, 2);
    Console.WriteLine();
    Memory.PrintMemory((nint)0x1410EC6CE, 2);
    Console.WriteLine();

    _isPrinted = true;
}
```

In Hedge Mod Manager, go to the Settings tab and click `Enable debug console`. Launch the game and once you get to the main menu, it should write some hex values to the console, please send a screenshot of the output so I can verify whether the `Disable FPS Limit` code actually installed.

**Comment by OmuNaki** [comment]
![image](https://github.com/user-attachments/assets/6e8f8d79-d18e-472f-8ac4-284fcb177e1b)
This is what it shows.

**Comment by hyperbx** [comment]
Looks like you have some overlay software installed that's trying to hook the graphics device.

Add the following to your `ExtraCodes.hmm` and press F5 at the Codes tab in Hedge Mod Manager to refresh, then enable it under the Uncategorised category.

```cs
Patch "Crash"
*(int*)0 = 0;
```

This will cause the game to crash on boot so we can generate a crash dump. Hold the Windows key and press R and enter `%APPDATA%` and hit enter, then navigate to `.\SEGA\SonicFrontiers\steam\crashpad_db\reports\` and send the latest `*.dmp` file in that directory. I'll be able to determine from there what application is doing this, in case that is the culprit.

**Comment by OmuNaki** [comment]
I booted up the game and it crashed but it didn't create a new `*.dmp` file, the latest one there is from July 25th this year.

**Comment by hyperbx** [comment]
Try checking `%LOCALAPPDATA%\CrashDumps\` in case it got put in there instead.

**Comment by OmuNaki** [comment]
[SonicFrontiers.exe.23884.dmp](https://github.com/user-attachments/files/17355792/SonicFrontiers.exe.23884.dmp)
There it was.

**Comment by hyperbx** [comment]
I don't see anything out of the ordinary in here, perhaps it's crashing too early. Try this;

```cs
Code "Crash"
//
    #lib "GameMode"
//
{
    if (GameMode.GetName() != "GameModeTitle")
        return;

    *(int*)0 = 0;
}
```

**Comment by OmuNaki** [comment]
[40f42b6f-e6ac-4db2-bcdd-c2b0d7de2f6b.dmp](https://github.com/user-attachments/files/17355821/40f42b6f-e6ac-4db2-bcdd-c2b0d7de2f6b.dmp)
Here.

**Comment by hyperbx** [comment]
Do you happen to use any of the following programs?

![image](https://github.com/user-attachments/assets/b91ed140-ad89-4ce1-a86d-d0fc1028c051)

The messages printed to the debug console come from a library called `goverlay` which injects an overlay into the game.

**Comment by OmuNaki** [comment]
I downloaded Medal recently, but I closed it during the tests we've been doing, and the problem has been going on since before downloading it. I have Guilded installed too but it's always closed.

**Comment by hyperbx** [comment]
> but I closed it during the tests we've been doing

That'd explain why I didn't see anything in the crash dumps. lol

So the code I sent all the way back at the beginning, are you able to see the output from that in the debug console now that it's not being spammed with `goverlay` messages?

**Comment by hyperbx** [comment]
It should output something like this.

![image](https://github.com/user-attachments/assets/ba8833f3-5452-4006-a2fa-e5b972ecfad8)

**Comment by OmuNaki** [comment]
![image](https://github.com/user-attachments/assets/c5773409-1ece-414a-b732-7616d69c65be)
It showed properly now lol

**Comment by hyperbx** [comment]
Looks like the `Disable FPS Limit` code is being installed properly.

This seems like it could be a software issue outside of the game itself, you may want to double-check your display settings and check out NVIDIA Control Panel to see if it's applying any limit to the game.

**Comment by OmuNaki** [comment]
Huh, I didn't even know Framerate could be limited with NVIDIA Control Panel, if I had known I would've checked there first.

![image](https://github.com/user-attachments/assets/e00d1c2f-3f66-4126-a7ea-37f6445dd6fa)

Thank you so much and sorry for taking up your time with what ended up being such a simple thing!

**Comment by hyperbx** [comment]
Haha nice, glad you got it sorted. No worries!
