### ISSUE TITLE
[Shadow Generations] [Code] Restore Stomp Bounce bug?

### ISSUE THREAD

**Issue by horay133** [hedge-dev/HMMCodes#169]
when using the Restore Stomp Bounce in game it locks the double jump after using it (if im using the Stomp Bounce i cant double jump after) but i can boost from it and then double jump so i think it a bug but I'm not sure

**Comment by hyperbx** [comment]
This behaviour is identical to how Stomp Bounce works in Sonic Frontiers.

I may work on state transition fixes in the future to address this, but considering it's not a bug with the code itself, I'll close this issue for now.
