### ISSUE TITLE
[Sonic Frontiers] Lua Library crashes

### ISSUE THREAD

**Issue by TrackerTD** [hedge-dev/HMMCodes#17]
Certain codes cause a crash (mainly noticed during the Giganto fight). Spoke to Hyper and after using a test code:
`Code "Test"
//
    #lib "Player"
//
{
    Console.WriteLine("Test");
}`

It seems it's related to the Lua library. Hyper is aware, I'm just putting this here for issue tracking purposes.

**Comment by HyperBE32** [comment]
Fixed in commit https://github.com/hedge-dev/HMMCodes/commit/909a14743468fbd9b3998b145c0bb277424c60d9.
