### ISSUE TITLE
[Suggestion] Split up the Tighter Jump Rotation codes for Shadow's Doom Powers

### ISSUE THREAD

**Issue by AllyJaxx** [hedge-dev/HMMCodes#172]
Really dislike the recent change to jump rotation in Doom Surf, would be nice if the codes were split off from the main tighter jump rotation code.

**Comment by hyperbx** [comment]
Addressed in commit https://github.com/hedge-dev/HMMCodes/commit/20423fe8a2b63c2b282b0933f3d56085ef04c023.
