### ISSUE TITLE
[Shadow Generations] Attempting to use a Homing Attack out of a Stomp Bounce does not work.

### ISSUE THREAD

**Issue by AllyJaxx** [hedge-dev/HMMCodes#173]
Attempting to homing attack out of a stomp bounce when using "Restore Stomp Bounce" does not work, this can be bypassed by using chaos spear, but it's still annoying nonetheless 

https://github.com/user-attachments/assets/cc876e4b-8882-433d-9e72-f87bd3824e06

**Comment by hyperbx** [comment]
Duplicate of https://github.com/hedge-dev/HMMCodes/issues/169.
