### ISSUE TITLE
[Shadow Generations] Always Use Movie Shadow Skin code bug report

### ISSUE THREAD

**Issue by CODEX0827** [hedge-dev/HMMCodes#184]
![image_2024-12-14_071215475](https://github.com/user-attachments/assets/b99600c8-6a58-4d7b-84ac-82003f531d0e)
in radical highway act 1 I'm just stuck in this point and cant do the level

Also almost all doom power are working a bit janky
Doom Spear - 100% works as intended

Doom Blast - have a long delay after using it (getting stuck like this for a bit)
![image_2024-12-14_072144879](https://github.com/user-attachments/assets/6f25bc29-7d1e-4aac-add1-905752feab24)

Doom Surf - feels slower and he goes under the water
![image_2024-12-14_072028688](https://github.com/user-attachments/assets/3676b7e7-4fe4-4dae-9a1a-87632bd078f1)

Doom Morph - 100% works as intended

Doom Wings - have a bit of a delay when activating

Doom Blast/Surf/Wings and Free Falling and sliding sections - missing animations all together and we can figure out why as movie shadow doesn't have those animations

**Comment by hyperbx** [comment]
The issue in Radical Highway Act 1 has been fixed as of commit https://github.com/hedge-dev/HMMCodes/commit/c4fae20ff1eae8d0042ea52980826e068b158016.

As for the rest, these can't really be addressed in code and may rely on animations existing in order to fix them. Closing...
