### ISSUE TITLE
[Bug] [SonicFrontiers] Game crashes when I manually load a save file

### ISSUE THREAD

**Issue by Shadowfan81** [hedge-dev/HMMCodes#19]
## Describe the issue/bug

The game crashes when I manually load a save file while using codes.

## Expected Behaviour

The game shouldn't crash on manual load.

## Additional Context

Codes used (tried having only one active at once) : 
- Patch "[Amy] Disable Card Spin Boost Transition" in "Animation" by "Hyper"
- Patch "[Knuckles] Disable Gliding Transition" in "Animation" by "Hyper"
- Patch "[Knuckles] Disable Stomp Transition" in "Animation" by "Hyper"
- Patch "[Tails] Disable Cyclone Transition" in "Animation" by "Hyper"
- Patch "[Tails] Disable Stomp Transition" in "Animation" by "Hyper"
- Code "Character Swapper (experimental)" in "Gameplay" by "Hyper, Skyth & Gordon Ramsay"

**Comment by HyperBE32** [comment]
Fixed as of commit https://github.com/hedge-dev/HMMCodes/commit/909a14743468fbd9b3998b145c0bb277424c60d9.
