### ISSUE TITLE
Physics Codes Break Frontiers  First Island  1.40

### ISSUE THREAD

**Issue by RinMaru** [hedge-dev/HMMCodes#23]
On the first island when you active the dialog "Thats just begging to be climbed, imagine the View" all movement controls are locked. I had Reduced homing delay and tighter drop dash and jump rotation enabled. I tried narrowing it down to the 3 but the issue never stopped unless i had them disabled period.

**Comment by HyperBE32** [comment]
Thanks for reporting, this appears to be an issue with `Retain Ground Velocity for Jump` when `Restrict movement during a monologue` is enabled in the game settings. Looking into it...

**Comment by HyperBE32** [comment]
Fixed in commit https://github.com/hedge-dev/HMMCodes/commit/501684babb3ea6af26a9880d2a20d70d00be3902.
