### ISSUE TITLE
[Sonic Frontiers] Character Swapper soft-locks mission progress in Chaos Island if Emerald is accidentally collected by character other than Sonic 

### ISSUE THREAD

**Issue by davewhiffen** [hedge-dev/HMMCodes#30]
Describe the issue/bug

Chaos Island, softlocked at 'Collect the Chaos Emerald'.

Accidentally soft-locked myself with Character Swapper.

I collected the Green Emerald (which is that Tails mini-game where you bash open crates and collect screws)-- as Knuckles,

So the Tails event has been registered as complete, but Knuckles has the green emerald (I can see when I switch to him and open my map)

So now I'm softlocked without a way to revert since I discovered too late.

Unless I can somehow spawn that enemy that steals emeralds, then have Knuckles lose it, and re-collect it as Sonic again.

Cheat Engine doesn't let you edit Emeralds, so that's out.

Will keep looking at a solution (and will backup my saves more often)
Expected Behaviour
Additional Context

**Comment by HyperBE32** [comment]
Character Swapper isn't intended to be a 100% playable experience and was more done for fun, keep your expectations reasonable.

**Comment by davewhiffen** [comment]
Oh absolutely! I'm having a blast with it!

**Comment by davewhiffen** [comment]
It was such a niche soft-lock I figured I'd share
