### ISSUE TITLE
[SonicFrontiers] 

### ISSUE THREAD

**Issue by Gemi1603** [hedge-dev/HMMCodes#37]
[HMM_Snapshot_00102023213308.txt](https://github.com/hedge-dev/HMMCodes/files/13099193/HMM_Snapshot_00102023213308.txt)

HMM Info:
```
    Version: 7.11-1
    Args: 
    StartDir: D:\steam\steamapps\common\SonicFrontiers\
    Process Level: User
    Game: Sonic Frontiers
    GameInstall: Sonic Frontiers
    Update Status: Up To Date
```

Exception:
```
    Message: Error Compiling Codes
    - Sonic Outfit Fixes\Always Load Outfit Data
        Error Unable to find dependency library 'Lua'


```

**Comment by HyperBE32** [comment]
Update your community codes.

**Comment by Gemi1603** [comment]
> Update your community codes.

Thank you so much lol, I def need to get used to using these things, I knew I was missing something now everything works fine!
