### ISSUE TITLE
[Sonic Frontiers] Issue with "Somersault Landing at High Velocity"

### ISSUE THREAD

**Issue by itsCaldee** [hedge-dev/HMMCodes#38]
Having the "Somersault Landing at High Velocity" HMM code enabled creates rare moments where Sonic doesn't stick to climbable walls. I'm not certain how many areas this occurs in, but I know that it at least breaks this platforming section in Ouranos as seen in the video linked. 

(The platforming section is left of the area that contains the final chaos emerald on Ouranos)

https://github.com/hedge-dev/HMMCodes/assets/148875235/f94efa86-ea56-4c31-835b-3b9fa7b9fcae

**Comment by HyperBE32** [comment]
Fixed in commit https://github.com/hedge-dev/HMMCodes/commit/0c01b444bce87c477624f13a0b7607a71a2e9682.
