### ISSUE TITLE
[Sonic Frontiers] Disable Cyber Space terrain flinging when using the Rocket Boost.

### ISSUE THREAD

**Issue by blue-person** [hedge-dev/HMMCodes#41]
When both the "[Cyber Space] Enable Terrain Flinging" and "[Cyber Space] Enable Air Tricks from Terrain" cheats are active, and Sonic uses the Rocket Boost in mid-air, he starts running in a straight line, breaking the levels designed with this mechanic, with the most noticeable impact in level 4-A.

**Comment by HyperBE32** [comment]
Fixed in commit https://github.com/hedge-dev/HMMCodes/commit/36674cebd96bc9c68ddf67d5a6965221a2f0e75e.
