### ISSUE TITLE
[SonicFrontiers] 

### ISSUE THREAD

**Issue by Comedorcasadas1999** [hedge-dev/HMMCodes#56]
Game crashes when trying to run Reforged combat newest version

[HMM_Snapshot_00112023150908.txt](https://github.com/hedge-dev/HMMCodes/files/13326153/HMM_Snapshot_00112023150908.txt)

HMM Info:
```
    Version: 7.12-2
    Args: 
    StartDir: E:\SteamLibrary\steamapps\common\SonicFrontiers
    Process Level: User
    Game: Sonic Frontiers
    GameInstall: Sonic Frontiers
    Update Status: Up To Date
```

Exception:
```
    Message: Error Compiling Codes
    - Reforged Combat\Knux Stuff
        Error @(6,23) CS0103: The name 'BlackboardItem' does not exist in the current context


```

**Comment by DeaTh-G** [comment]
As the issue seems to be coming from a mod, please contact the author of the `Reforged Combat` mod.
