### ISSUE TITLE
[Sonic Frontiers] v1.41 compatibility report

### ISSUE THREAD

**Issue by ActualMandM** [hedge-dev/HMMCodes#77]
Please report any and all code/library compatibility issues with v1.41 here.
When testing, make sure to only be running a singular code to prevent any false reports.

- [x] Smooth Camera (v1.40)
- [x] Fix RenderDoc Captures (v1.40)
- [x] Character Swapper
- [x] Classic Jump Deceleration
- [x] SonicParameters
- [x] AmyParameters
- [x] KnucklesParameters
- [x] TailsParameters
- [x] PhotoModeParameters
- [x] Disable Distance Limit
- [x] Disable Orbit Camera (experimental)

**Comment by ActualMandM** [comment]
Character Swapper crashes when trying to switch characters.

https://github.com/hedge-dev/HMMCodes/assets/15317421/fe0979ee-7efc-45ae-8738-f9557c6510c7

**Comment by mikeploythai** [comment]
Classic Jump Deceleration and Reduced Homing Delay makes the game break when you're about to load into gameplay

**Comment by ActualMandM** [comment]
I was only able to replicate Classic Jump Deceleration crashing the game, the other 2 seemed to work fine for me.

**Comment by mikeploythai** [comment]
> I was only able to replicate Classic Jump Deceleration crashing the game, the other 2 seemed to work fine for me.

There’s a chance that combinations of active codes conflict with each other, resulting in the game crashing

**Comment by ecksdii** [comment]
Always Unlocked Spin Dash works but causes Sonic to always use his "dying" idle animation, like in Rhea.

**Comment by ecksdii** [comment]
Always Respawn Enemies doesn't seem to work at all.

**Comment by HyperBE32** [comment]
All reported and remaining invalid signatures have been fixed as of recent commits. Closing...
